{% set pyproject = load_file_data("pyproject.toml") %}

package:
  name: {{ pyproject['project']['name'] }}
  version: {{ pyproject['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: pip install . --no-deps --ignore-installed -vv
  {% if 'scripts' in pyproject.get('project', {}) %}
  entry_points:
    {% for script_name, entry_point in pyproject['project']['scripts'].items() %}
    - {{ script_name }}={{ entry_point }}
    {% endfor %}
  {% endif %}

requirements:
  host:
    - python {{ pyproject['project']['requires-python'] }}
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    - pytest
  imports:
    - suxarray

about:
  home: {{ pyproject['project']['urls']['Homepage'] }}
  summary: {{ pyproject['project']['description'] }}
  license: MIT
