# Copied from https://coderefinery.github.io/documentation/gh_workflow/ and
# modified to use the GitHub Actions sphinx-build action
name: docs
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: >
          pip install uxarray pandas xarray numba netcdf4 shapely holoviews
          datashader click sphinx sphinx_rtd_theme nbsphinx
          sphinx-versioned-docs
      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs suxarray
          sphinx-versioned --output docs/_build --local-conf docs/conf.py --branch "v2024.06" --main-branch main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          force_orphan: true
