# Copied from https://coderefinery.github.io/documentation/gh_workflow/ and
# modified to use the GitHub Actions sphinx-build action
name: docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme nbsphinx
      - name: Sphinx build
        run: |
          sphinx-build docs docs_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
          force_orphan: true
